### ISSUE TITLE
Icons are not displayed on Linux

### ISSUE THREAD

**Issue by dongri** [jonathontoon/tweet-tray#104]
## Expected Behavior

![screenshot from 2018-02-11 16-28-54](https://user-images.githubusercontent.com/878993/36071297-9b63d66e-0f4f-11e8-962a-f29dfb04db9e.png)

## Current Behavior

![screenshot from 2018-02-11 16-31-03](https://user-images.githubusercontent.com/878993/36071296-935557d6-0f4f-11e8-8a95-2dfa170641bb.png)

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package | 1.0.3        |
| Runtime | Linux  |
| Package Manager | yarn |
| Operating System | Ubuntu (elementary OS) |

**Comment by jonathontoon** [comment]
Thanks @dongri. We need all the Linux help we can get. 🙇
