### ISSUE TITLE
Tweet Tray blocks Ctrl/Cmd-Enter input in other Electron apps

### ISSUE THREAD

**Issue by Jon-Indico** [jonathontoon/tweet-tray#121]
## Expected Behavior

Ctrl/Cmd-Enter should work in any application

## Current Behavior

When Tweet Tray is running, the Ctrl/Cmd-Enter key combination doesn't work in [Gitkraken](https://www.gitkraken.com/) and VS Code. I'm assuming this has something to do with them all being Electron apps.

## Possible Solution

I'm assuming there's a (global?) keyboard hook that should only be active when the UI of Tweet Tray is shown

## Context
I've stopped using Tweet Tray on my dev box

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | 1.0.3
| Operating System | Windows 10 1709 & macOS 10.13 High Sierra

**Comment by jonathontoon** [comment]
Thanks a lot for reporting @jonindico! I'll have a fix for this in the next release.

**Comment by thetwopct** [comment]
Also experiencing this - effecting CMD+Enter sending in Gmail via Safari and also in Mailplane 3
