### ISSUE TITLE
Error message when opening main UI from tray icon

### ISSUE THREAD

**Issue by Jon-Indico** [jonathontoon/tweet-tray#156]
## Expected Behavior

Main UI should be opened without error when clicking the tray icon.

## Current Behavior

After updating to version 1.1, I'm seeing the following error message when trying to launch the main UI from the tray icon.

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'x' of null
    at u.showWindow (C:\Users\Jon\AppData\Local\Programs\tweet-tray\resources\app.asar\webpack:\app\MenuBarManager.js:211:17)
    at Tray._tray.on (C:\Users\Jon\AppData\Local\Programs\tweet-tray\resources\app.asar\webpack:\app\MenuBarManager.js:134:3)
    at emitThree (events.js:135:13)
    at Tray.emit (events.js:216:7)

[OK]
```

I've tried uninstalling and reinstalling, and uninstalling deleting tweet-tray folders %appdata%/tweet-tray and %localappdata%/programs/tweet-tray. I've also rebooted since installing.

## Context

I'm assuming it's related to calculating some coordinates. So I'm including some info about screen resolution, etc.

Info | Details
--- | ---
Screen resolution | 1920x1280
Scaling factor | 125%
No. of screens | Usually 2, but only 1 at the moment
Taskbar placement | Left side of main screen only (did not work with taskbar on the bottom either)

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | 1.1
| Runtime          |
| Package Manager  |
| Operating System | Windows 10 1709 (16299.309)

**Comment by jonathontoon** [comment]
Cheers for the report @Jon-Indico will look into a fix this week.

**Comment by jonathontoon** [comment]
@Jon-Indico Resolved in v1.1.1. Closing this out for now.

**Comment by ow** [comment]
@jonathontoon I'm going to bump this one to re-open it: on a Surface Book 2 with Insider Preview RS5 - 17704. I get the same error at 4K and can't get it to open, but I also understand this is an insider build. FWIW, I waited from the previous build, which was also affected, to see if it was a one-off.

**Comment by jonathontoon** [comment]
@jonathontoon thanks for letting me know. It basically has to do with the layout logic for how I position the window based on the taskbar. Makes sense if the issue appears on 4K because it probably has insane resolutions that go beyond my measurements.

Any chance you can fork it, run the dev version and see what the console output is giving you?

**Comment by jonathontoon** [comment]
I released a [small update](https://github.com/jonathontoon/tweet-tray/releases/tag/v1.1.4) for Windows only that hopefully will resolve this. Feel free anyone to reopen this issue if you have any problems still with this release.
