### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by riotherio** [jonathontoon/tweet-tray#162]
A keyboard shortcut to quickly open the tweet tray window to would be pretty sweet, for all platforms.
I often find myself looking for the icon in the menu bar (on Mac).

**Comment by jonathontoon** [comment]
@riotherio try ⌘ + ⇧ + Alt + T. Does it work for you? 

Pretty lengthy I know, but wanted to make sure it didn't conflict with other apps. Could always make it custom in the future I guess...

**Comment by riotherio** [comment]
Ohhh cool! 
Forgot about that one! 😎

**Comment by riotherio** [comment]
Would be cool for customization in the future for sure.
