### ISSUE TITLE
Linux - Clicking system tray icon doesn't show window

### ISSUE THREAD

**Issue by emlyn-h** [jonathontoon/tweet-tray#172]
## Expected Behavior

Clicking on the system tray icon should show the main window.

## Current Behavior

Clicking on the system tray icon does nothing .

## Possible Solution

Looks like it's probably the same as this [electron issue](https://github.com/electron/electron/issues/6773), so doesn't look like there's a solve.

Using the Ctrl-Alt-Shift-T shortcut to force the window to show.

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | 1.1.2
| Runtime          |
| Package Manager  |
| Operating System | Kubuntu 16.04

**Comment by jonathontoon** [comment]
Thanks @emlyn-h! 

I tested this about a month ago on Ubuntu without issue. With all the variants of Linux I'm aiming for minimum support until I get someone to handle the majority of the work.

**Comment by emlyn-h** [comment]
One option might be to change the behaviour on Linux.

Context menu on the icon seem to work for me (right click menu style).  But it's an extra user click, which feels a bit redundant.

Example: https://github.com/emlyn-h/tweet-tray/commit/326ac39c54a5bb1fbebd1af76aa5908f9227889b

**Comment by jonathontoon** [comment]
@emlyn-h if you reckon this will run fine on most common distros then I'd be happy to merge it. It's good to make sure Tweet Tray is passable for Linux users, as opposed to relying on a keyboard shortcut. 😄

**Comment by emlyn-h** [comment]
@jonathontoon yeah, might be a safest.  The [docs](https://electronjs.org/docs/api/tray) seem to have a bunch of Linux limitations listed.
