### ISSUE TITLE
Hitting the Escape button dismisses the app

### ISSUE THREAD

**Issue by hos4m** [jonathontoon/tweet-tray#173]
## Expected Behavior
Hitting the Escape button will dismiss the app. 

## Current Behavior
Hitting the Escape button doesn't do anything and the user has to press outside of the app with the mouse.

## Your Environment
MacOS 10.12.6

**Comment by jonathontoon** [comment]
Thanks for the report @hos4m. This is by design, for now. I'd like for Tweet Tray to be easily exit-able rather than have to hit a specific button or icon to close the window.
