### ISSUE TITLE
No Tweet Tray cask install found 

### ISSUE THREAD

**Issue by BillTribble** [jonathontoon/tweet-tray#181]
Not working in OSX. 

> Error: No available Cask for tweet-tray
> Error: nothing to install

Also: Hi Jonathan!

**Comment by jonathontoon** [comment]
@riotherio handles Tweet Tray's cask integration, maybe he can help you out. 😄

**Comment by riotherio** [comment]
I'll handle it

**Comment by BillTribble** [comment]
Boom, teamwork :)

**Comment by jonathontoon** [comment]
@riomarmccartney any chance yet to take a look at this?

**Comment by riomarmccartney** [comment]
@jonathontoon I'll look into it now! Sorry it took so long

**Comment by riomarmccartney** [comment]
Wow! https://github.com/Homebrew/homebrew-cask/pull/47181 has been done some time ago and it seems to work and download the latest versions of Tweet-tray 1.1.3
<img width="755" alt="screen shot 2018-08-21 at 8 49 16 pm" src="https://user-images.githubusercontent.com/3750705/44399770-b6bdf000-a583-11e8-9689-2340ff5240ae.png">

Also, I've looked up the recent docs and updating the cask is pretty easy too: Quoting from https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md


> ## Updating a Cask
> 
> Notice an application that's out-of-date in Homebrew-Cask? In most cases, it's very simple to update it. We have a [script](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) that will ask for the new version number, and take care of updating the Cask file and submitting a pull request to us:
> 
> ```bash
> # install and setup script - only needed once
> brew install vitorgalvao/tiny-scripts/cask-repair
> cask-repair --help
> 
> # use to update <outdated_cask>
> cask-repair <outdated_cask>


> If there is a more complicated change, or there is a case where `cask-repair` fails (for example, where a Cask uses a [`url do` block](https://github.com/Homebrew/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/audacity.rb#L5#L15) or the [`language` stanza](https://github.com/Homebrew/homebrew-cask/blob/306b8fbd9502036f1ca742f70c569d8677b62403/Casks/firefox.rb#L4L74)), you can also follow the steps in [Adding a Cask](doc/development/adding_a_cask.md) to do the same thing manually. Remember to update the `version` and `shasum` values.

**Comment by jonathontoon** [comment]
@riomarmccartney thanks mate!
