### ISSUE TITLE
Global shortcut fails in MacOSX Mojave

### ISSUE THREAD

**Issue by serialjoy** [jonathontoon/tweet-tray#183]
## Expected Behavior
The CMD+Ctrl+Return is not working on MacOSX 10.14 - Mojave with version 1.1.3

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | https://github.com/jonathontoon/tweet-tray/releases/download/v1.1.3/tweet-tray-1.1.3.dmg 
| Operating System | 10.14 Beta (18A336e)

**Comment by jonathontoon** [comment]
@serialjoy thanks for reporting. I'm going to wait for the time being for until Mojave has a production release. That way I can be sure what ever fix administered will hopefully be final.

**Comment by serialjoy** [comment]
Makes sense. Thank you for doing this.

**Comment by jonathontoon** [comment]
@serialjoy I'll see if I can take look into this sometime this weekend. Can at least find out what's needed to fix it.

**Comment by jonathontoon** [comment]
@serialjoy I just checked this out this afternoon with 1.1.3 on the latest build of Mojave and I can’t seem to receive any errors or failures with the keyboard shortcuts. Could you check these again and let me know? Thanks!

**Comment by serialjoy** [comment]
Sure - I'll take a look.

**Comment by jonathontoon** [comment]
Closing this for now. As tested myself on macOS 10.14.2 both shortcuts Shift+Option+CMD+T (Open Tweet Tray) and CMD + Enter (Sending Tweet) both are operational.
