### ISSUE TITLE
No reaction after installed

### ISSUE THREAD

**Issue by lessfish** [jonathontoon/tweet-tray#188]
after installing, I click the icon in the menu bar, but no reaction, see below:

macos 10.13.2

![](https://ws4.sinaimg.cn/large/006tNc79gy1fytoqed0wdg30hu0hzwop.gif)

thanks

**Comment by jonathontoon** [comment]
Hi @hanzichi thanks for reporting the issue. Which version of Tweet Tray do you have installed? Any chance you can set up the Tweet Tray project locally and tell me any error messages being shown in the development console?

I am running only macOS 10.14.2 on my own machine.

**Comment by hanzichi** [comment]
get an error after `yarn dev`

![](https://ws3.sinaimg.cn/large/006tNc79ly1fyvzvpby3rj31gk0u019h.jpg)

**Comment by jonathontoon** [comment]
@hanzichi oops, looks like I broke the build by mistake. Update your local master or develop branch and you should no longer see this error.

**Comment by hanzichi** [comment]
same error after `git pull`, feel sad

**Comment by jonathontoon** [comment]
@hanzichi Okay. Did you try running `rm -rf node_modules` in the root folder and run `yarn install` again?

**Comment by hanzichi** [comment]
ok, after running, then see another error..

![image](https://user-images.githubusercontent.com/10890665/50734662-3b30a880-11dd-11e9-9642-39eae26fec33.png)

**Comment by jonathontoon** [comment]
@hanzichi Thanks! I'm going to need a little more information however. 

Did you see the Tweet Tray logo appear in the macOS taskbar? Did the Electron/Chrome developer tools launch and show any errors? Did any errors appear in the command line (where you ran `yarn start`)?

**Comment by hanzichi** [comment]
yes, I'm in mainland China

maybe the same issue why I cannot start it from the release version?

but I really don't know how to set the proxy settings from the [doc](https://github.com/jonathontoon/tweet-tray#settings), can you explain it in detail? thanks!

**Comment by survivor303** [comment]
same kind of behavior on Windows. "Log in with Twitter" dosnt do anything but "Quit Tweet Tray" button works. and with latest build 1.1.4

**Comment by jonathontoon** [comment]
@survivor303 hmm 1.1.4 should be working fine, I have it running myself on Windows. But I'll check it out to see what's up. Which OS version do you have? Also, you're not in Mainland China right? Just incase there's some connection there...

**Comment by survivor303** [comment]
@jonathontoon no im not from china.. im from finland :) My Windows is win10pro insider build 18309.

**Comment by jonathontoon** [comment]
@survivor303 Great, thanks. I found your issue for 1.1.4. Sorry about that. Will update you here once I've updated the bundle under that release.

**Comment by jonathontoon** [comment]
@survivor303 [Updated bundle is up](https://github.com/jonathontoon/tweet-tray/releases/tag/v1.1.4).

**Comment by jonathontoon** [comment]
@hanzichi seems like your issue is the proxy yeah. I personally haven't had a use for it yet (however we added the partial option for those who may really want it). 

@emlyn-h did the original development, if something isn't clear perhaps he can answer some of your questions.

**Comment by hanzichi** [comment]
@jonathontoon I do not think so ,  in my first pic, I cannot open the Login page as @survivor303 , I also use the latest 1.1.4 version, same issue?

**Comment by jonathontoon** [comment]
@hanzichi 1.1.4 bundle is fixed now - you've tried downloading the exe again and installing it on a Windows machine, but have the same issue?

**Comment by hanzichi** [comment]
@jonathontoon my fault, I use the latest macOS version which is 1.1.3
