### ISSUE TITLE
Typo in Japanese translation for `report_issue_action`

### ISSUE THREAD

**Issue by hashedhyphen** [jonathontoon/tweet-tray#194]
## Expected Behavior

A correct Japanese translation for `report_issue_action` would be "問題やバグを報告する".

## Current Behavior

`app/localizations/ja.json` defines it as "問題やハグを報告する"

## Possible Solution

The Japanese word for "bug" is "バグ", not "ハグ". So it would be sufficient to edit `ja.json`.

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          |
| Runtime          |
| Package Manager  |
| Operating System |

**Comment by jonathontoon** [comment]
Fixed in 1.1.5.
