### ISSUE TITLE
Can't paste into the app

### ISSUE THREAD

**Issue by hugomd** [jonathontoon/tweet-tray#38]
Hey! 👋

Firstly, thanks for starting an awesome open source project 🙏

When I first started the app and was prompted to sign in with Twitter, I couldn't paste in my password nor my 2FA code, and have just tried copy pasting something as a tweet, and that hasn't worked either.

Having had a quick Google, it seems like a fairly [well documented issue](https://pracucci.com/atom-electron-enable-copy-and-paste.html), and requires setting up an app menu.

I'll have a go at fixing this myself if I have time ✌️

**Comment by jonathontoon** [comment]
Thanks a ton for that @hugomd! I’m tracking that already over on #29. Will have a fix ready for release fairly soon.
