### ISSUE TITLE
Fix Twitter logo spacing & balance in resources

### ISSUE THREAD

**Issue by riotherio** [jonathontoon/tweet-tray#50]
<img width="162" alt="screen shot 2018-02-04 at 3 11 40 pm" src="https://user-images.githubusercontent.com/3750705/35774796-bc13762c-09bd-11e8-9508-c0ddcc08ec42.png">

Currently, the icon used in resources like App icon, tray icon and more, aren't optically aligned. Twitter recently updated their brand guides that includes circular icons and square icons. I'll be replacing with those instead of the existing ones :)

---

<img width="1000" alt="screen shot 2018-02-04 at 12 42 30 pm" src="https://user-images.githubusercontent.com/3750705/35774762-65085380-09bc-11e8-8c93-3d32828139b8.png">

From Twitter's [Brand Guidelines](https://about.twitter.com/en_us/company/brand-resources.html)

**Comment by jonathontoon** [comment]
Good stuff @riotherio! I'll take a look.

**Comment by jonathontoon** [comment]
Released in 1.0.2.
