### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by ChangeUsername** [jonathontoon/tweet-tray#57]
Can you add configurable proxy support? Without it I can't use this.

**Comment by mt-toon** [comment]
Probably pretty low on the list, but if you'd like to offer some more explanation perhaps someone could pick up the task.

**Comment by jonathontoon** [comment]
Probably low on the list for now, but I'd love to more on why you'd need it. Perhaps something with a bit more knowledge in the area can pick up the task.

**Comment by ChangeUsername** [comment]
I'm working in China several times a year and because I don't want to use a VPN (because it mostly doesn't work anyways) I'm using an SSH connection to create a socks5 proxy.

**Comment by jonathontoon** [comment]
@ChangeUsername Thanks for the reply, that makes good sense. I don't have much experience concerning such an implementation so I will just leave it open for someone else to try for now.

**Comment by jonathontoon** [comment]
@ChangeUsername coming up in the next release will be Proxy support, but it's only possible by compiling your own version of the app. Currently you can read @emlyn-h's instructions in the README of `develop`.

**Comment by emlyn-Resn** [comment]
@jonathontoon the instructions to set the proxy, will work with the released version of the app. It's just that you'll have to launch the app from the command line.

**Comment by jonathontoon** [comment]
@emlyn-Resn gotcha thanks for the help!
