### ISSUE TITLE
Work on a new logo to differentiate from Twitters core branding

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/tweet-tray#67]

**Comment by ggamel** [comment]
My suggestion is a pigeon. This would be a stark contrast to the generic bird iconography.

What are the assets needed for all the app's branding/identity needs?
Which files/sizes do you expect/need?

**Comment by jonathontoon** [comment]
I think @riotherio is going to work on a proposal. Assigning it to him for now.

**Comment by ggamel** [comment]
@jonathontoon Sounds good 😁 Looking forward to seeing it evolve!
