### ISSUE TITLE
Means to add alt text when posting images

### ISSUE THREAD

**Issue by ollicle** [jonathontoon/tweet-tray#74]
There is a means to include alt text for uploaded images in the Twitter client API

[Alt text support for Twitter Cards and the REST API](https://blog.twitter.com/developer/en_us/a/2016/alt-text-support-for-twitter-cards-and-the-rest-api.html)

**Comment by jonathontoon** [comment]
A good suggestion, I didn't know this existed.

I wish Twitter hadn't split everything up via separate endpoints though, makes the time it takes to actually post a tweet longer. 

Will need to take some time to consider how to design this, for describing alt text every time I want to post an image gets really cumbersome.
