### ISSUE TITLE
Autocomplete for @mentions

### ISSUE THREAD

**Issue by pugson** [jonathontoon/tweet-tray#78]
Would be great to have autocomplete when mentioning someone just like Twitter.

<img width="401" alt="screen shot 2018-02-07 at 6 45 58 pm" src="https://user-images.githubusercontent.com/6843656/35932137-33b1606a-0c37-11e8-83dc-ff1929846b64.png">

**Comment by jonathontoon** [comment]
Thanks for the suggestion. Marking this as a duplicate of #34 for now.

**Comment by joeflateau** [comment]
@jonathontoon just arrived here after trying to @ someone in Tweet Tray... I noticed you marked this as a duplicate of "When Settings overlay is clicked dismiss the component". Perhaps you meant a different issue? This is very different from dismissing.

**Comment by jonathontoon** [comment]
Oops, thanks @joeflateau.
