### ISSUE TITLE
Tweet Tray appears in the middle of the screen instead of above the taskbar

### ISSUE THREAD

**Issue by thatakke** [jonathontoon/tweet-tray#82]
![image](https://user-images.githubusercontent.com/36261841/35966916-8d9868fc-0cbf-11e8-8f4b-7d98fb254164.png)

So it's covering my Thor now 😅

I'm on Windows 10, Insider Build 17083, and tweet tray version is 1.0.2

**Comment by jonathontoon** [comment]
Thanks @thatakke! Since the Insider build is beta there's probably a lot which Electron still is incompatible with. I'll see if there some issues already raised.

**Comment by jonathontoon** [comment]
Also noticed from a few anecdotal reports this also occurs on Linux.

**Comment by jonathontoon** [comment]
@thatakke got some reports that this has also been happening for people running multiple displays. Is this the case with your setup?

**Comment by maxart** [comment]
Using Tweet Tray 1.0.3 (fresh install), on (non-insider) Windows 10 Pro, version 1709.
Taskbar is at the bottom of the screen, set to "small taskbar button". Using a SB2, with an external monitor attached. :(

![screenshot_70](https://user-images.githubusercontent.com/34616/36075950-6411dda4-0f0a-11e8-9840-cea3454073c1.png)

+ @jonathontoon

**Comment by thatakke** [comment]
@jonathontoon Nope, I'm sorry 😕 I only have one monitor 🤷🏻‍♂️

**Comment by jonathontoon** [comment]
@maxart nice find, I was able to repro this by also turning on`Small Taskbar Buttons`. I'll look into what's causing it and release a hotfix.
