### ISSUE TITLE
Configure tweet tray to be installed with cask

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/tweet-tray#86]
Seems easy enough based off [this](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md).

**Comment by riotherio** [comment]
https://github.com/caskroom/homebrew-cask/pull/45043

**Comment by riotherio** [comment]
<img width="824" alt="screen shot 2018-03-22 at 1 46 15" src="https://user-images.githubusercontent.com/3750705/37723880-da66637c-2d72-11e8-825c-75f7089608b4.png">

**Comment by jonathontoon** [comment]
LGTM!
