### ISSUE TITLE
Correct window position when tray is pushed aside

### ISSUE THREAD

**Issue by riotherio** [jonathontoon/tweet-tray#90]
## Expected Behavior

<img width="300" src="https://user-images.githubusercontent.com/3750705/36010622-bdf45ce6-0d95-11e8-88a7-11af74f7f4d4.png">

## Current Behavior

<img width="300" src="https://user-images.githubusercontent.com/3750705/36010624-c307b3b8-0d95-11e8-98ab-1ac7c71a3ee6.png">

The tray is pushed aside inside the menu bar on macOS, so when launching the tweet-tray window, it's pushed to the boundary of the screen. It should have a small padding between the side and the window, so that it doesn't look cut off. 

## Possible Solution

When the window is pushed aside & touching the border of the screen, it should have the same 20px spacing from the menu bar, between the window and the screen border.

## Context

Better window placement

## Your Environment 

Develop branch

| Software         | Version(s) |
| ---------------- | ---------- |
| Runtime          | 1.0.2
| MacOS | 10.13.3 (17D47)

**Comment by jonathontoon** [comment]
Yeah this seems to be in Windows too. Be great if you could fix this.
![tray](https://user-images.githubusercontent.com/1197942/36018044-94515128-0dbd-11e8-8e90-b67dfc0554ce.PNG)
