### ISSUE TITLE
Please provide an AppImage for Linux on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [jonathontoon/tweet-tray#93]
https://github.com/jonathontoon/tweet-tray/blob/ddf7bea6ce68760e62fb7849e1a7a70e5d22b9a5/package.json#L72

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by jonathontoon** [comment]
Hi @probonopd, thanks for being passionate about Linux, Tweet Tray definitely needs more help on that platform. 

Unfortunately I'm not sure what you are exactly requesting here, for if you check out the [releases](https://github.com/jonathontoon/tweet-tray/releases/) an AppImage is already being provided for Linux builds.

If there's something specific or extra that could be provided concerning AppImages please create an separate issue and it will get prioritized in upcoming milestones.

**Comment by jonathontoon** [comment]
Hi @probonopd, thanks for being passionate about Linux, Tweet Tray definitely needs more help on that platform. 

Unfortunately I'm not sure what you are exactly requesting here, for if you check out the [releases](https://github.com/jonathontoon/tweet-tray/releases/) an AppImage is already being provided for Linux builds.

If there's something specific or extra that could be provided concerning AppImages please create an separate issue and it will get prioritized in upcoming milestones.

**Comment by probonopd** [comment]
> Unfortunately I'm not sure what you are exactly requesting here, for if you check out the releases an AppImage is already being provided for Linux builds.

I don't see an AppImage here, just a Linux zip:

![](https://user-images.githubusercontent.com/2480569/36060062-23fcf478-0e39-11e8-85bd-13f6ab93fda7.png)

Please advise.

**Comment by probonopd** [comment]
Actually turns out the Linux zip contains an AppImage. Please don't put the AppImage into a zip. The reasons are explained at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake:

> While it may be tempting to avoid users having to set the execute permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

**Comment by jonathontoon** [comment]
Okay, that's good feedback. Easy enough to upload separate downloads. I will support that format in the upcoming releases. 

For `.deb`'s do you know any preferred ways to distribute them? i.e.: compressed or not.

**Comment by probonopd** [comment]
Not compressed. They are already a compressed archive, too. Thanks.
